### ISSUE TITLE
优化小建议

### ISSUE THREAD

**Issue by loong0306** [ywgx/ki#1]
终端下，进入pod选择Container后，bash无法通过tab进行填充，希望可以补充bash。辛苦

**Comment by loong0306** [comment]
找到解决方案了：https://www.jianshu.com/p/7fcfcb0edeec

**Comment by ywgx** [comment]
感谢建议

因为考虑到大部分容器有 sh ，而不是 bash ,&nbsp;
可以看代码登陆容器的命令，把 sh 改成 bash 就是你要的效果


--------------原始邮件--------------
发件人："dragon ***@***.***&gt;;
发送时间：2022年12月30日(星期五) 下午5:15
收件人："ywgx/ki" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[ywgx/ki] 优化小建议 (Issue #1)
-----------------------------------

 

 
终端下，进入pod选择Container后，bash无法通过tab进行填充，希望可以补充bash。辛苦
